export default {
  LOAD_COLLECTIONS: "LOAD_COLLECTIONS",
  ADD_COLLECTION: "ADD_COLLECTION",
  ADD_ELEMENT: "ADD_ELEMENT",
  LOAD_SHARED_COLLECTIONS: "LOAD_SHARED_COLLECTIONS",
  LOAD_USERS: "LOAD_USERS",
  LOAD_SHARED_COLLECTIONS_RELATED_TO_COLLECTIONS:
    "LOAD_SHARED_COLLECTIONS_RELATED_TO_COLLECTIONS",
  COLLECTION_MADE_PUBLIC: "COLLECTION_MADE_PUBLIC",
};
